name: ft_intent_merchants

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy files to Droplet via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: root
        key: ${{ secrets.DO_SSH_KEY }}
        source: "."
        target: "/var/www/merchants.foxridge.fun"
  
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: root  
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          cd /var/www/merchants.foxridge.fun
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          chown -R www-data:www-data /var/www/merchants.foxridge.fun
